### ISSUE TITLE
Clase Scanner

### ISSUE THREAD

**Issue by franlu** [tonibruna/AccesoDatos#3]
Busca información en la documentación oficial sobre la clase Scanner. Crea un paquete en tu proyecto llamado utilidades y a continuación escribe una clase que contenga un ejemplo de Scanner.
Cuando lo tengas, lo llevas al repositorio y cierras esta tarea.

**Comment by tonibruna** [comment]
Entendido Fran.

Lo único que no podré subirlo a GitHub hasta el lunes en clase, ya que
desde mi ordenador no he podido sincronizarlo todavía.

Buen puente!

**Comment by franlu** [comment]
@tonibruna Doy por echo que ya tienes el ejercicio resuelto. Cierro la incidencia :smile:

**Comment by tonibruna** [comment]
Esta hecho Fran. Se puede cerrar la incidencia 😉
