### ISSUE TITLE
Problemas con github

### ISSUE THREAD

**Issue by tonibruna** [tonibruna/AccesoDatos#4]
Buenos dias Fran. 

Yo y mi lucha con el github... estoy intentando subir todos los progresos desde casa al github con los pasos que vimos en el video tutorial. El ultimo dia creia tenerlo vinculado perfectamente. 
Hago el Commit and Push y da los pasos correctos como si lo estuviera colgando en github (me pide cada vez contraseña y usuario)... pero no lo cuelga. 
Si te parece el proximo dia llevo el pòrtatil y me echas un cable a ver si lo dejamos perfecto.

La practica que tenemos que subir hoy, si te parece te la paso de otra manera.

**Comment by franlu** [comment]
Hola Toni,

tráete el portátil y lo dejamos configurado esta tarde.

s2!

**Comment by tonibruna** [comment]
Esta tarde no podre ir a clase. Lo hacemos el lunes si te parece. 

Saludos

**Comment by franlu** [comment]
> Esta tarde no podre ir a clase. Lo hacemos el lunes si te parece.
> 
> Saludos

De acuerdo!
